### ISSUE TITLE
Using deprecated size() method

### ISSUE THREAD

**Issue by Prze-moC** [Pretius/apex-enhanced-notifications#5]
https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-size-removed

**Comment by alexbasnett** [comment]
Just installed for the first time but looks like the above is a stopper for this plugin until an update is released?

Is there a work around in the meantime?

`jquery-3.4.1.js?v=20.1.0.00.13:3841 **jQuery.Deferred exception: insertInto.size is not a function TypeError: insertInto.size** is not a function
    at $.<computed>.<computed>._create (https://yyyyyyyyyy.xxxxx.zzz:8443/ords/sandbox/r/100/files/plugin/1884035544494763926/v34/pretius.notification.js:68:21)
    at $.<computed>.<computed>._create (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:474:25)
    at $.<computed>.<computed>._createWidget (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:671:8)
    at new $.<computed>.<computed> (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:429:9)
    at HTMLDivElement.<anonymous> (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:611:30)
    at Function.each (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery/3.4.1/jquery-3.4.1.js?v=20.1.0.00.13:367:19)
    at jQuery.fn.init.each (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery/3.4.1/jquery-3.4.1.js?v=20.1.0.00.13:202:17)
    at jQuery.fn.init.$.fn.<computed> [as notification] (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:603:9)
    at $.<computed>.<computed>.pushNotification (https://yyyyyyyyyy.xxxxx.zzz:8443/ords/sandbox/r/100/files/plugin/1884035544494763926/v34/pretius.notifications.js:44:41)
    at $.<computed>.<computed>.pushNotification (https://yyyyyyyyyy.xxxxx.zzz:8443/i/libraries/jquery-ui/1.12.1/jquery-ui-apex.js?v=20.1.0.00.13:474:25) undefined

**Uncaught TypeError: insertInto.size is not a function**
    at $.<computed>.<computed>._create (pretius.notification.js:68)
    at $.<computed>.<computed>._create (jquery-ui-apex.js?v=20.1.0.00.13:474)
    at $.<computed>.<computed>._createWidget (jquery-ui-apex.js?v=20.1.0.00.13:671)
    at new $.<computed>.<computed> (jquery-ui-apex.js?v=20.1.0.00.13:429)
    at HTMLDivElement.<anonymous> (jquery-ui-apex.js?v=20.1.0.00.13:611)
    at Function.each (jquery-3.4.1.js?v=20.1.0.00.13:367)
    at jQuery.fn.init.each (jquery-3.4.1.js?v=20.1.0.00.13:202)
    at jQuery.fn.init.$.fn.<computed> [as notification] (jquery-ui-apex.js?v=20.1.0.00.13:603)
    at $.<computed>.<computed>.pushNotification (pretius.notifications.js:44)
    at $.<computed>.<computed>.pushNotification (jquery-ui-apex.js?v=20.1.0.00.13:474)`

**Comment by Prze-moC** [comment]
I have the corrected version of the plug-in (APEX 20.2 compatible + several spelling mistakes corrected) but I do not know how to put it into the repository.
Here: 
[dynamic_action_plugin_pretius_com_notifications.zip](https://github.com/Pretius/apex-enhanced-notifications/files/6021070/dynamic_action_plugin_pretius_com_notifications.zip)

**Comment by alexbasnett** [comment]
Thanks. 

I'm on 20.1 and your version is giving me a compatability error. 

I will upgrade to 20.2 and install your version.
